name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config --global user.name "Yash"
          git config --global user.email "sisodiya98yash@gmail.com"
          git add -A
          git commit -m "Update 3D Contribution Graph" || echo "No changes to commit"
          git push
